[tool.poetry]
name = "esercizi"
version = "0.1.0"
description = ""
authors = ["scrbn72 <carlo.lombardi95@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
